!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_fortran_module_num_threads (num_threadsf2pywra&
     &p)
      use fortran_module, only : num_threads
      integer num_threadsf2pywrap
      num_threadsf2pywrap = num_threads()
      end subroutine f2pywrap_fortran_module_num_threads
      subroutine f2pywrap_fortran_module_multiindices (n, m, degs, n_deg&
     &, n_idx, n_idx_by_deg, idx_ptr, idx, stratifier, f2py_idx_ptr_d0, &
     &f2py_idx_d0, f2py_stratifier_d0)
      use fortran_module, only : multiindices
      integer n
      integer n_deg
      integer n_idx
      integer f2py_idx_ptr_d0
      integer f2py_idx_d0
      integer f2py_stratifier_d0
      integer m(n)
      integer degs(n_deg)
      integer n_idx_by_deg(n_deg)
      integer idx_ptr(f2py_idx_ptr_d0)
      integer idx(f2py_idx_d0)
      integer stratifier(f2py_stratifier_d0)
      call multiindices(n, m, degs, n_deg, n_idx, n_idx_by_deg, idx_ptr,&
     & idx, stratifier)
      end subroutine f2pywrap_fortran_module_multiindices
      
      subroutine f2pyinitfortran_module(f2pysetupfunc)
      use fortran_module, only : simulate_time_series
      use fortran_module, only : simulate_mutations
      use fortran_module, only : discrete_fit
      use fortran_module, only : discrete_fit_i
      use fortran_module, only : continuous_fit
      use fortran_module, only : continuous_fit_i
      interface 
      subroutine f2pywrap_fortran_module_num_threads (num_threadsf2pywra&
     &p, num_threads)
      integer num_threads
      integer num_threadsf2pywrap
      end subroutine f2pywrap_fortran_module_num_threads 
      subroutine f2pywrap_fortran_module_multiindices (n, m, degs, n_deg&
     &, n_idx, n_idx_by_deg, idx_ptr, idx, stratifier, f2py_idx_ptr_d0, &
     &f2py_idx_d0, f2py_stratifier_d0)
      integer n
      integer n_deg
      integer n_idx
      integer f2py_idx_ptr_d0
      integer f2py_idx_d0
      integer f2py_stratifier_d0
      integer m(n)
      integer degs(n_deg)
      integer n_idx_by_deg(n_deg)
      integer idx_ptr(f2py_idx_ptr_d0)
      integer idx(f2py_idx_d0)
      integer stratifier(f2py_stratifier_d0)
      end subroutine f2pywrap_fortran_module_multiindices
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_fortran_module_num_threads,f2pywrap_fo&
     &rtran_module_multiindices,simulate_time_series,simulate_mutations,&
     &discrete_fit,discrete_fit_i,continuous_fit,continuous_fit_i)
      end subroutine f2pyinitfortran_module


