/* File: fortran_modulemodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Jul 11 18:45:47 2018
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fortran_module_error;
static PyObject *fortran_module_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(fortran_module_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fortran_module_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fortran_module_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** num_threads ********************************/
static char doc_f2py_rout_fortran_module_fortran_module_num_threads[] = "\
n = num_threads()\n\nWrapper for ``num_threads``.\
\n\nReturns\n-------\n"
"n : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_fortran_module_fortran_module_num_threads(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int num_threads = 0;
  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":fortran_module.fortran_module.num_threads",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
  /* Processing variable num_threads */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&num_threads);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",num_threads);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable num_threads */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of num_threads *****************************/

/******************************** multiindices ********************************/
static char doc_f2py_rout_fortran_module_fortran_module_multiindices[] = "\
idx_ptr,idx,stratifier = multiindices(m,degs,n_idx,n_idx_by_deg,[n,n_deg])\n\nWrapper for ``multiindices``.\
\n\nParameters\n----------\n"
"m : input rank-1 array('i') with bounds (n)\n"
"degs : input rank-1 array('i') with bounds (n_deg)\n"
"n_idx : input int\n"
"n_idx_by_deg : input rank-1 array('i') with bounds (n_deg)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(m)\n"
"n_deg : input int, optional\n    Default: len(degs)\n"
"\nReturns\n-------\n"
"idx_ptr : rank-1 array('i') with bounds (f2py_idx_ptr_d0)\n"
"idx : rank-1 array('i') with bounds (f2py_idx_d0)\n"
"stratifier : rank-1 array('i') with bounds (f2py_stratifier_d0)";
/* #declfortranroutine# */
static PyObject *f2py_rout_fortran_module_fortran_module_multiindices(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  int *m = NULL;
  npy_intp m_Dims[1] = {-1};
  const int m_Rank = 1;
  PyArrayObject *capi_m_tmp = NULL;
  int capi_m_intent = 0;
  PyObject *m_capi = Py_None;
  int *degs = NULL;
  npy_intp degs_Dims[1] = {-1};
  const int degs_Rank = 1;
  PyArrayObject *capi_degs_tmp = NULL;
  int capi_degs_intent = 0;
  PyObject *degs_capi = Py_None;
  int n_deg = 0;
  PyObject *n_deg_capi = Py_None;
  int n_idx = 0;
  PyObject *n_idx_capi = Py_None;
  int *n_idx_by_deg = NULL;
  npy_intp n_idx_by_deg_Dims[1] = {-1};
  const int n_idx_by_deg_Rank = 1;
  PyArrayObject *capi_n_idx_by_deg_tmp = NULL;
  int capi_n_idx_by_deg_intent = 0;
  PyObject *n_idx_by_deg_capi = Py_None;
  int *idx_ptr = NULL;
  npy_intp idx_ptr_Dims[1] = {-1};
  const int idx_ptr_Rank = 1;
  PyArrayObject *capi_idx_ptr_tmp = NULL;
  int capi_idx_ptr_intent = 0;
  int *idx = NULL;
  npy_intp idx_Dims[1] = {-1};
  const int idx_Rank = 1;
  PyArrayObject *capi_idx_tmp = NULL;
  int capi_idx_intent = 0;
  int *stratifier = NULL;
  npy_intp stratifier_Dims[1] = {-1};
  const int stratifier_Rank = 1;
  PyArrayObject *capi_stratifier_tmp = NULL;
  int capi_stratifier_intent = 0;
  int f2py_idx_ptr_d0 = 0;
  int f2py_idx_d0 = 0;
  int f2py_stratifier_d0 = 0;
  static char *capi_kwlist[] = {"m","degs","n_idx","n_idx_by_deg","n","n_deg",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OO:fortran_module.fortran_module.multiindices",\
    capi_kwlist,&m_capi,&degs_capi,&n_idx_capi,&n_idx_by_deg_capi,&n_capi,&n_deg_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable degs */
  ;
  capi_degs_intent |= F2PY_INTENT_IN;
  capi_degs_tmp = array_from_pyobj(NPY_INT,degs_Dims,degs_Rank,capi_degs_intent,degs_capi);
  if (capi_degs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 2nd argument `degs' of fortran_module.fortran_module.multiindices to C/Fortran array" );
  } else {
    degs = (int *)(PyArray_DATA(capi_degs_tmp));

  /* Processing variable idx */
  ;
  capi_idx_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_idx_tmp = array_from_pyobj(NPY_INT,idx_Dims,idx_Rank,capi_idx_intent,Py_None);
  if (capi_idx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `idx' of fortran_module.fortran_module.multiindices to C/Fortran array" );
  } else {
    idx = (int *)(PyArray_DATA(capi_idx_tmp));

  /* Processing variable idx_ptr */
  ;
  capi_idx_ptr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_idx_ptr_tmp = array_from_pyobj(NPY_INT,idx_ptr_Dims,idx_ptr_Rank,capi_idx_ptr_intent,Py_None);
  if (capi_idx_ptr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `idx_ptr' of fortran_module.fortran_module.multiindices to C/Fortran array" );
  } else {
    idx_ptr = (int *)(PyArray_DATA(capi_idx_ptr_tmp));

  /* Processing variable m */
  ;
  capi_m_intent |= F2PY_INTENT_IN;
  capi_m_tmp = array_from_pyobj(NPY_INT,m_Dims,m_Rank,capi_m_intent,m_capi);
  if (capi_m_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 1st argument `m' of fortran_module.fortran_module.multiindices to C/Fortran array" );
  } else {
    m = (int *)(PyArray_DATA(capi_m_tmp));

  /* Processing variable n_idx */
    f2py_success = int_from_pyobj(&n_idx,n_idx_capi,"fortran_module.fortran_module.multiindices() 3rd argument (n_idx) can't be converted to int");
  if (f2py_success) {
  /* Processing variable stratifier */
  ;
  capi_stratifier_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_stratifier_tmp = array_from_pyobj(NPY_INT,stratifier_Dims,stratifier_Rank,capi_stratifier_intent,Py_None);
  if (capi_stratifier_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `stratifier' of fortran_module.fortran_module.multiindices to C/Fortran array" );
  } else {
    stratifier = (int *)(PyArray_DATA(capi_stratifier_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = len(m); else
    f2py_success = int_from_pyobj(&n,n_capi,"fortran_module.fortran_module.multiindices() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(m)>=n,"len(m)>=n","1st keyword n","multiindices:n=%d",n) {
  /* Processing variable n_deg */
  if (n_deg_capi == Py_None) n_deg = len(degs); else
    f2py_success = int_from_pyobj(&n_deg,n_deg_capi,"fortran_module.fortran_module.multiindices() 2nd keyword (n_deg) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(degs)>=n_deg,"len(degs)>=n_deg","2nd keyword n_deg","multiindices:n_deg=%d",n_deg) {
  /* Processing variable n_idx_by_deg */
  n_idx_by_deg_Dims[0]=n_deg;
  capi_n_idx_by_deg_intent |= F2PY_INTENT_IN;
  capi_n_idx_by_deg_tmp = array_from_pyobj(NPY_INT,n_idx_by_deg_Dims,n_idx_by_deg_Rank,capi_n_idx_by_deg_intent,n_idx_by_deg_capi);
  if (capi_n_idx_by_deg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 4th argument `n_idx_by_deg' of fortran_module.fortran_module.multiindices to C/Fortran array" );
  } else {
    n_idx_by_deg = (int *)(PyArray_DATA(capi_n_idx_by_deg_tmp));

  /* Processing variable f2py_idx_ptr_d0 */
  f2py_idx_ptr_d0 = shape(idx_ptr, 0);
  /* Processing variable f2py_idx_d0 */
  f2py_idx_d0 = shape(idx, 0);
  /* Processing variable f2py_stratifier_d0 */
  f2py_stratifier_d0 = shape(stratifier, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&n,m,degs,&n_deg,&n_idx,n_idx_by_deg,idx_ptr,idx,stratifier,&f2py_idx_ptr_d0,&f2py_idx_d0,&f2py_stratifier_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNN",capi_idx_ptr_tmp,capi_idx_tmp,capi_stratifier_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_stratifier_d0 */
  /* End of cleaning variable f2py_idx_d0 */
  /* End of cleaning variable f2py_idx_ptr_d0 */
  if((PyObject *)capi_n_idx_by_deg_tmp!=n_idx_by_deg_capi) {
    Py_XDECREF(capi_n_idx_by_deg_tmp); }
  }  /*if (capi_n_idx_by_deg_tmp == NULL) ... else of n_idx_by_deg*/
  /* End of cleaning variable n_idx_by_deg */
  } /*CHECKSCALAR(len(degs)>=n_deg)*/
  } /*if (f2py_success) of n_deg*/
  /* End of cleaning variable n_deg */
  } /*CHECKSCALAR(len(m)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  }  /*if (capi_stratifier_tmp == NULL) ... else of stratifier*/
  /* End of cleaning variable stratifier */
  } /*if (f2py_success) of n_idx*/
  /* End of cleaning variable n_idx */
  if((PyObject *)capi_m_tmp!=m_capi) {
    Py_XDECREF(capi_m_tmp); }
  }  /*if (capi_m_tmp == NULL) ... else of m*/
  /* End of cleaning variable m */
  }  /*if (capi_idx_ptr_tmp == NULL) ... else of idx_ptr*/
  /* End of cleaning variable idx_ptr */
  }  /*if (capi_idx_tmp == NULL) ... else of idx*/
  /* End of cleaning variable idx */
  if((PyObject *)capi_degs_tmp!=degs_capi) {
    Py_XDECREF(capi_degs_tmp); }
  }  /*if (capi_degs_tmp == NULL) ... else of degs*/
  /* End of cleaning variable degs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of multiindices ****************************/

/**************************** simulate_time_series ****************************/
static char doc_f2py_rout_fortran_module_fortran_module_simulate_time_series[] = "\
x = simulate_time_series(w,m,l,degs)\n\nWrapper for ``simulate_time_series``.\
\n\nParameters\n----------\n"
"w : input rank-2 array('d') with bounds (m_sum,n_s)\n"
"m : input rank-1 array('i') with bounds (n)\n"
"l : input int\n"
"degs : input rank-1 array('i') with bounds (n_deg)\n"
"\nReturns\n-------\n"
"x : rank-2 array('i') with bounds (n,l)";
/*  */
static PyObject *f2py_rout_fortran_module_fortran_module_simulate_time_series(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *w = NULL;
  npy_intp w_Dims[2] = {-1, -1};
  const int w_Rank = 2;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  PyObject *w_capi = Py_None;
  int m_sum = 0;
  int n_s = 0;
  int n = 0;
  int *m = NULL;
  npy_intp m_Dims[1] = {-1};
  const int m_Rank = 1;
  PyArrayObject *capi_m_tmp = NULL;
  int capi_m_intent = 0;
  PyObject *m_capi = Py_None;
  int l = 0;
  PyObject *l_capi = Py_None;
  int *degs = NULL;
  npy_intp degs_Dims[1] = {-1};
  const int degs_Rank = 1;
  PyArrayObject *capi_degs_tmp = NULL;
  int capi_degs_intent = 0;
  PyObject *degs_capi = Py_None;
  int n_deg = 0;
  int *x = NULL;
  npy_intp x_Dims[2] = {-1, -1};
  const int x_Rank = 2;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  static char *capi_kwlist[] = {"w","m","l","degs",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:fortran_module.fortran_module.simulate_time_series",\
    capi_kwlist,&w_capi,&m_capi,&l_capi,&degs_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable degs */
  ;
  capi_degs_intent |= F2PY_INTENT_IN;
  capi_degs_tmp = array_from_pyobj(NPY_INT,degs_Dims,degs_Rank,capi_degs_intent,degs_capi);
  if (capi_degs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 4th argument `degs' of fortran_module.fortran_module.simulate_time_series to C/Fortran array" );
  } else {
    degs = (int *)(PyArray_DATA(capi_degs_tmp));

  /* Processing variable m */
  ;
  capi_m_intent |= F2PY_INTENT_IN;
  capi_m_tmp = array_from_pyobj(NPY_INT,m_Dims,m_Rank,capi_m_intent,m_capi);
  if (capi_m_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 2nd argument `m' of fortran_module.fortran_module.simulate_time_series to C/Fortran array" );
  } else {
    m = (int *)(PyArray_DATA(capi_m_tmp));

  /* Processing variable l */
    f2py_success = int_from_pyobj(&l,l_capi,"fortran_module.fortran_module.simulate_time_series() 3rd argument (l) can't be converted to int");
  if (f2py_success) {
  /* Processing variable w */
  ;
  capi_w_intent |= F2PY_INTENT_IN;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 1st argument `w' of fortran_module.fortran_module.simulate_time_series to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

  /* Processing variable m_sum */
  m_sum = shape(w,0);
  /* Processing variable n */
  n = len(m);
  /* Processing variable x */
  x_Dims[0]=n,x_Dims[1]=l;
  capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_x_tmp = array_from_pyobj(NPY_INT,x_Dims,x_Rank,capi_x_intent,Py_None);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `x' of fortran_module.fortran_module.simulate_time_series to C/Fortran array" );
  } else {
    x = (int *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable n_s */
  n_s = shape(w,1);
  /* Processing variable n_deg */
  n_deg = len(degs);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(w,&m_sum,&n_s,&n,m,&l,degs,&n_deg,x);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_x_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable n_deg */
  /* End of cleaning variable n_s */
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  /* End of cleaning variable n */
  /* End of cleaning variable m_sum */
  if((PyObject *)capi_w_tmp!=w_capi) {
    Py_XDECREF(capi_w_tmp); }
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
  if((PyObject *)capi_m_tmp!=m_capi) {
    Py_XDECREF(capi_m_tmp); }
  }  /*if (capi_m_tmp == NULL) ... else of m*/
  /* End of cleaning variable m */
  if((PyObject *)capi_degs_tmp!=degs_capi) {
    Py_XDECREF(capi_degs_tmp); }
  }  /*if (capi_degs_tmp == NULL) ... else of degs*/
  /* End of cleaning variable degs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of simulate_time_series ************************/

/***************************** simulate_mutations *****************************/
static char doc_f2py_rout_fortran_module_fortran_module_simulate_mutations[] = "\
x,y = simulate_mutations(w,m,l,degs)\n\nWrapper for ``simulate_mutations``.\
\n\nParameters\n----------\n"
"w : input rank-2 array('d') with bounds (m_sum,n_s)\n"
"m : input rank-1 array('i') with bounds (n)\n"
"l : input int\n"
"degs : input rank-1 array('i') with bounds (n_deg)\n"
"\nReturns\n-------\n"
"x : rank-2 array('i') with bounds (n,l)\n"
"y : rank-2 array('i') with bounds (n,l)";
/*  */
static PyObject *f2py_rout_fortran_module_fortran_module_simulate_mutations(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *w = NULL;
  npy_intp w_Dims[2] = {-1, -1};
  const int w_Rank = 2;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  PyObject *w_capi = Py_None;
  int m_sum = 0;
  int n_s = 0;
  int n = 0;
  int *m = NULL;
  npy_intp m_Dims[1] = {-1};
  const int m_Rank = 1;
  PyArrayObject *capi_m_tmp = NULL;
  int capi_m_intent = 0;
  PyObject *m_capi = Py_None;
  int l = 0;
  PyObject *l_capi = Py_None;
  int *degs = NULL;
  npy_intp degs_Dims[1] = {-1};
  const int degs_Rank = 1;
  PyArrayObject *capi_degs_tmp = NULL;
  int capi_degs_intent = 0;
  PyObject *degs_capi = Py_None;
  int n_deg = 0;
  int *x = NULL;
  npy_intp x_Dims[2] = {-1, -1};
  const int x_Rank = 2;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  int *y = NULL;
  npy_intp y_Dims[2] = {-1, -1};
  const int y_Rank = 2;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  static char *capi_kwlist[] = {"w","m","l","degs",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:fortran_module.fortran_module.simulate_mutations",\
    capi_kwlist,&w_capi,&m_capi,&l_capi,&degs_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable degs */
  ;
  capi_degs_intent |= F2PY_INTENT_IN;
  capi_degs_tmp = array_from_pyobj(NPY_INT,degs_Dims,degs_Rank,capi_degs_intent,degs_capi);
  if (capi_degs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 4th argument `degs' of fortran_module.fortran_module.simulate_mutations to C/Fortran array" );
  } else {
    degs = (int *)(PyArray_DATA(capi_degs_tmp));

  /* Processing variable m */
  ;
  capi_m_intent |= F2PY_INTENT_IN;
  capi_m_tmp = array_from_pyobj(NPY_INT,m_Dims,m_Rank,capi_m_intent,m_capi);
  if (capi_m_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 2nd argument `m' of fortran_module.fortran_module.simulate_mutations to C/Fortran array" );
  } else {
    m = (int *)(PyArray_DATA(capi_m_tmp));

  /* Processing variable l */
    f2py_success = int_from_pyobj(&l,l_capi,"fortran_module.fortran_module.simulate_mutations() 3rd argument (l) can't be converted to int");
  if (f2py_success) {
  /* Processing variable w */
  ;
  capi_w_intent |= F2PY_INTENT_IN;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 1st argument `w' of fortran_module.fortran_module.simulate_mutations to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

  /* Processing variable m_sum */
  m_sum = shape(w,0);
  /* Processing variable n */
  n = len(m);
  /* Processing variable y */
  y_Dims[0]=n,y_Dims[1]=l;
  capi_y_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_y_tmp = array_from_pyobj(NPY_INT,y_Dims,y_Rank,capi_y_intent,Py_None);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `y' of fortran_module.fortran_module.simulate_mutations to C/Fortran array" );
  } else {
    y = (int *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable x */
  x_Dims[0]=n,x_Dims[1]=l;
  capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_x_tmp = array_from_pyobj(NPY_INT,x_Dims,x_Rank,capi_x_intent,Py_None);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `x' of fortran_module.fortran_module.simulate_mutations to C/Fortran array" );
  } else {
    x = (int *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable n_s */
  n_s = shape(w,1);
  /* Processing variable n_deg */
  n_deg = len(degs);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(w,&m_sum,&n_s,&n,m,&l,degs,&n_deg,x,y);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_x_tmp,capi_y_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable n_deg */
  /* End of cleaning variable n_s */
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  /* End of cleaning variable n */
  /* End of cleaning variable m_sum */
  if((PyObject *)capi_w_tmp!=w_capi) {
    Py_XDECREF(capi_w_tmp); }
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
  if((PyObject *)capi_m_tmp!=m_capi) {
    Py_XDECREF(capi_m_tmp); }
  }  /*if (capi_m_tmp == NULL) ... else of m*/
  /* End of cleaning variable m */
  if((PyObject *)capi_degs_tmp!=degs_capi) {
    Py_XDECREF(capi_degs_tmp); }
  }  /*if (capi_degs_tmp == NULL) ... else of degs*/
  /* End of cleaning variable degs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of simulate_mutations *************************/

/******************************** discrete_fit ********************************/
static char doc_f2py_rout_fortran_module_fortran_module_discrete_fit[] = "\
w,disc,iter = discrete_fit(x,y,m_x,m_y,m_y_sum,degs,x_oh_pinv1,x_oh_pinv2,x_oh_pinv3,iters,overfit,impute)\n\nWrapper for ``discrete_fit``.\
\n\nParameters\n----------\n"
"x : input rank-2 array('i') with bounds (n_x,l)\n"
"y : input rank-2 array('i') with bounds (n_y,l)\n"
"m_x : input rank-1 array('i') with bounds (n_x)\n"
"m_y : input rank-1 array('i') with bounds (n_y)\n"
"m_y_sum : input int\n"
"degs : input rank-1 array('i') with bounds (n_deg)\n"
"x_oh_pinv1 : input rank-2 array('d') with bounds (l,x_oh_rank)\n"
"x_oh_pinv2 : input rank-1 array('d') with bounds (x_oh_rank)\n"
"x_oh_pinv3 : input rank-2 array('d') with bounds (x_oh_rank,n_s)\n"
"iters : input int\n"
"overfit : input int\n"
"impute : input int\n"
"\nReturns\n-------\n"
"w : rank-2 array('d') with bounds (m_y_sum,n_s)\n"
"disc : rank-2 array('d') with bounds (n_y,iters)\n"
"iter : rank-1 array('i') with bounds (n_y)";
/*  */
static PyObject *f2py_rout_fortran_module_fortran_module_discrete_fit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,int*,int*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int *x = NULL;
  npy_intp x_Dims[2] = {-1, -1};
  const int x_Rank = 2;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  int *y = NULL;
  npy_intp y_Dims[2] = {-1, -1};
  const int y_Rank = 2;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n_x = 0;
  int n_y = 0;
  int *m_x = NULL;
  npy_intp m_x_Dims[1] = {-1};
  const int m_x_Rank = 1;
  PyArrayObject *capi_m_x_tmp = NULL;
  int capi_m_x_intent = 0;
  PyObject *m_x_capi = Py_None;
  int *m_y = NULL;
  npy_intp m_y_Dims[1] = {-1};
  const int m_y_Rank = 1;
  PyArrayObject *capi_m_y_tmp = NULL;
  int capi_m_y_intent = 0;
  PyObject *m_y_capi = Py_None;
  int m_y_sum = 0;
  PyObject *m_y_sum_capi = Py_None;
  int l = 0;
  int *degs = NULL;
  npy_intp degs_Dims[1] = {-1};
  const int degs_Rank = 1;
  PyArrayObject *capi_degs_tmp = NULL;
  int capi_degs_intent = 0;
  PyObject *degs_capi = Py_None;
  int n_deg = 0;
  double *x_oh_pinv1 = NULL;
  npy_intp x_oh_pinv1_Dims[2] = {-1, -1};
  const int x_oh_pinv1_Rank = 2;
  PyArrayObject *capi_x_oh_pinv1_tmp = NULL;
  int capi_x_oh_pinv1_intent = 0;
  PyObject *x_oh_pinv1_capi = Py_None;
  double *x_oh_pinv2 = NULL;
  npy_intp x_oh_pinv2_Dims[1] = {-1};
  const int x_oh_pinv2_Rank = 1;
  PyArrayObject *capi_x_oh_pinv2_tmp = NULL;
  int capi_x_oh_pinv2_intent = 0;
  PyObject *x_oh_pinv2_capi = Py_None;
  double *x_oh_pinv3 = NULL;
  npy_intp x_oh_pinv3_Dims[2] = {-1, -1};
  const int x_oh_pinv3_Rank = 2;
  PyArrayObject *capi_x_oh_pinv3_tmp = NULL;
  int capi_x_oh_pinv3_intent = 0;
  PyObject *x_oh_pinv3_capi = Py_None;
  int x_oh_rank = 0;
  int n_s = 0;
  int iters = 0;
  PyObject *iters_capi = Py_None;
  int overfit = 0;
  PyObject *overfit_capi = Py_None;
  int impute = 0;
  PyObject *impute_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[2] = {-1, -1};
  const int w_Rank = 2;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  double *disc = NULL;
  npy_intp disc_Dims[2] = {-1, -1};
  const int disc_Rank = 2;
  PyArrayObject *capi_disc_tmp = NULL;
  int capi_disc_intent = 0;
  int *iter = NULL;
  npy_intp iter_Dims[1] = {-1};
  const int iter_Rank = 1;
  PyArrayObject *capi_iter_tmp = NULL;
  int capi_iter_intent = 0;
  static char *capi_kwlist[] = {"x","y","m_x","m_y","m_y_sum","degs","x_oh_pinv1","x_oh_pinv2","x_oh_pinv3","iters","overfit","impute",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOO:fortran_module.fortran_module.discrete_fit",\
    capi_kwlist,&x_capi,&y_capi,&m_x_capi,&m_y_capi,&m_y_sum_capi,&degs_capi,&x_oh_pinv1_capi,&x_oh_pinv2_capi,&x_oh_pinv3_capi,&iters_capi,&overfit_capi,&impute_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable degs */
  ;
  capi_degs_intent |= F2PY_INTENT_IN;
  capi_degs_tmp = array_from_pyobj(NPY_INT,degs_Dims,degs_Rank,capi_degs_intent,degs_capi);
  if (capi_degs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 6th argument `degs' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    degs = (int *)(PyArray_DATA(capi_degs_tmp));

  /* Processing variable iters */
    f2py_success = int_from_pyobj(&iters,iters_capi,"fortran_module.fortran_module.discrete_fit() 10th argument (iters) can't be converted to int");
  if (f2py_success) {
  /* Processing variable x_oh_pinv2 */
  ;
  capi_x_oh_pinv2_intent |= F2PY_INTENT_IN;
  capi_x_oh_pinv2_tmp = array_from_pyobj(NPY_DOUBLE,x_oh_pinv2_Dims,x_oh_pinv2_Rank,capi_x_oh_pinv2_intent,x_oh_pinv2_capi);
  if (capi_x_oh_pinv2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 8th argument `x_oh_pinv2' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    x_oh_pinv2 = (double *)(PyArray_DATA(capi_x_oh_pinv2_tmp));

  /* Processing variable overfit */
    overfit = (int)PyObject_IsTrue(overfit_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable impute */
    impute = (int)PyObject_IsTrue(impute_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_INT,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 1st argument `x' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    x = (int *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable m_y_sum */
    f2py_success = int_from_pyobj(&m_y_sum,m_y_sum_capi,"fortran_module.fortran_module.discrete_fit() 5th argument (m_y_sum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n_x */
  n_x = shape(x,0);
  /* Processing variable m_x */
  m_x_Dims[0]=n_x;
  capi_m_x_intent |= F2PY_INTENT_IN;
  capi_m_x_tmp = array_from_pyobj(NPY_INT,m_x_Dims,m_x_Rank,capi_m_x_intent,m_x_capi);
  if (capi_m_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 3rd argument `m_x' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    m_x = (int *)(PyArray_DATA(capi_m_x_tmp));

  /* Processing variable x_oh_rank */
  x_oh_rank = len(x_oh_pinv2);
  /* Processing variable x_oh_pinv3 */
  x_oh_pinv3_Dims[0]=x_oh_rank;
  capi_x_oh_pinv3_intent |= F2PY_INTENT_IN;
  capi_x_oh_pinv3_tmp = array_from_pyobj(NPY_DOUBLE,x_oh_pinv3_Dims,x_oh_pinv3_Rank,capi_x_oh_pinv3_intent,x_oh_pinv3_capi);
  if (capi_x_oh_pinv3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 9th argument `x_oh_pinv3' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    x_oh_pinv3 = (double *)(PyArray_DATA(capi_x_oh_pinv3_tmp));

  /* Processing variable l */
  l = shape(x,1);
  /* Processing variable x_oh_pinv1 */
  x_oh_pinv1_Dims[0]=l,x_oh_pinv1_Dims[1]=x_oh_rank;
  capi_x_oh_pinv1_intent |= F2PY_INTENT_IN;
  capi_x_oh_pinv1_tmp = array_from_pyobj(NPY_DOUBLE,x_oh_pinv1_Dims,x_oh_pinv1_Rank,capi_x_oh_pinv1_intent,x_oh_pinv1_capi);
  if (capi_x_oh_pinv1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 7th argument `x_oh_pinv1' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    x_oh_pinv1 = (double *)(PyArray_DATA(capi_x_oh_pinv1_tmp));

  /* Processing variable y */
  y_Dims[1]=l;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_INT,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 2nd argument `y' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    y = (int *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable n_deg */
  n_deg = len(degs);
  /* Processing variable n_y */
  n_y = shape(y,0);
  /* Processing variable n_s */
  n_s = shape(x_oh_pinv3,1);
  /* Processing variable disc */
  disc_Dims[0]=n_y,disc_Dims[1]=iters;
  capi_disc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_disc_tmp = array_from_pyobj(NPY_DOUBLE,disc_Dims,disc_Rank,capi_disc_intent,Py_None);
  if (capi_disc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `disc' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    disc = (double *)(PyArray_DATA(capi_disc_tmp));

  /* Processing variable iter */
  iter_Dims[0]=n_y;
  capi_iter_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iter_tmp = array_from_pyobj(NPY_INT,iter_Dims,iter_Rank,capi_iter_intent,Py_None);
  if (capi_iter_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `iter' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    iter = (int *)(PyArray_DATA(capi_iter_tmp));

  /* Processing variable m_y */
  m_y_Dims[0]=n_y;
  capi_m_y_intent |= F2PY_INTENT_IN;
  capi_m_y_tmp = array_from_pyobj(NPY_INT,m_y_Dims,m_y_Rank,capi_m_y_intent,m_y_capi);
  if (capi_m_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 4th argument `m_y' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    m_y = (int *)(PyArray_DATA(capi_m_y_tmp));

  /* Processing variable w */
  w_Dims[0]=m_y_sum,w_Dims[1]=n_s;
  capi_w_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `w' of fortran_module.fortran_module.discrete_fit to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,y,&n_x,&n_y,m_x,m_y,&m_y_sum,&l,degs,&n_deg,x_oh_pinv1,x_oh_pinv2,x_oh_pinv3,&x_oh_rank,&n_s,&iters,&overfit,&impute,w,disc,iter);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNN",capi_w_tmp,capi_disc_tmp,capi_iter_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  if((PyObject *)capi_m_y_tmp!=m_y_capi) {
    Py_XDECREF(capi_m_y_tmp); }
  }  /*if (capi_m_y_tmp == NULL) ... else of m_y*/
  /* End of cleaning variable m_y */
  }  /*if (capi_iter_tmp == NULL) ... else of iter*/
  /* End of cleaning variable iter */
  }  /*if (capi_disc_tmp == NULL) ... else of disc*/
  /* End of cleaning variable disc */
  /* End of cleaning variable n_s */
  /* End of cleaning variable n_y */
  /* End of cleaning variable n_deg */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_x_oh_pinv1_tmp!=x_oh_pinv1_capi) {
    Py_XDECREF(capi_x_oh_pinv1_tmp); }
  }  /*if (capi_x_oh_pinv1_tmp == NULL) ... else of x_oh_pinv1*/
  /* End of cleaning variable x_oh_pinv1 */
  /* End of cleaning variable l */
  if((PyObject *)capi_x_oh_pinv3_tmp!=x_oh_pinv3_capi) {
    Py_XDECREF(capi_x_oh_pinv3_tmp); }
  }  /*if (capi_x_oh_pinv3_tmp == NULL) ... else of x_oh_pinv3*/
  /* End of cleaning variable x_oh_pinv3 */
  /* End of cleaning variable x_oh_rank */
  if((PyObject *)capi_m_x_tmp!=m_x_capi) {
    Py_XDECREF(capi_m_x_tmp); }
  }  /*if (capi_m_x_tmp == NULL) ... else of m_x*/
  /* End of cleaning variable m_x */
  /* End of cleaning variable n_x */
  } /*if (f2py_success) of m_y_sum*/
  /* End of cleaning variable m_y_sum */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of impute*/
  /* End of cleaning variable impute */
  } /*if (f2py_success) of overfit*/
  /* End of cleaning variable overfit */
  if((PyObject *)capi_x_oh_pinv2_tmp!=x_oh_pinv2_capi) {
    Py_XDECREF(capi_x_oh_pinv2_tmp); }
  }  /*if (capi_x_oh_pinv2_tmp == NULL) ... else of x_oh_pinv2*/
  /* End of cleaning variable x_oh_pinv2 */
  } /*if (f2py_success) of iters*/
  /* End of cleaning variable iters */
  if((PyObject *)capi_degs_tmp!=degs_capi) {
    Py_XDECREF(capi_degs_tmp); }
  }  /*if (capi_degs_tmp == NULL) ... else of degs*/
  /* End of cleaning variable degs */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of discrete_fit ****************************/

/******************************* discrete_fit_i *******************************/
static char doc_f2py_rout_fortran_module_fortran_module_discrete_fit_i[] = "\
w,disc,iter = discrete_fit_i(i1,i2,s,y,m_y,x_oh_pinv1,x_oh_pinv2,x_oh_pinv3,iters,overfit,impute,[n_idx,l,x_oh_rank,n_s])\n\nWrapper for ``discrete_fit_i``.\
\n\nParameters\n----------\n"
"i1 : input int\n"
"i2 : input int\n"
"s : input rank-2 array('i') with bounds (n_idx,l)\n"
"y : input rank-1 array('i') with bounds (l)\n"
"m_y : input int\n"
"x_oh_pinv1 : input rank-2 array('d') with bounds (l,x_oh_rank)\n"
"x_oh_pinv2 : input rank-1 array('d') with bounds (x_oh_rank)\n"
"x_oh_pinv3 : input rank-2 array('d') with bounds (x_oh_rank,n_s)\n"
"iters : input int\n"
"overfit : input int\n"
"impute : input int\n"
"\nOther Parameters\n----------------\n"
"n_idx : input int, optional\n    Default: shape(s,0)\n"
"l : input int, optional\n    Default: shape(s,1)\n"
"x_oh_rank : input int, optional\n    Default: shape(x_oh_pinv1,1)\n"
"n_s : input int, optional\n    Default: shape(x_oh_pinv3,1)\n"
"\nReturns\n-------\n"
"w : rank-2 array('d') with bounds (m_y,n_s)\n"
"disc : rank-1 array('d') with bounds (iters)\n"
"iter : int";
/*  */
static PyObject *f2py_rout_fortran_module_fortran_module_discrete_fit_i(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,int*,int*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int i1 = 0;
  PyObject *i1_capi = Py_None;
  int i2 = 0;
  PyObject *i2_capi = Py_None;
  int *s = NULL;
  npy_intp s_Dims[2] = {-1, -1};
  const int s_Rank = 2;
  PyArrayObject *capi_s_tmp = NULL;
  int capi_s_intent = 0;
  PyObject *s_capi = Py_None;
  int n_idx = 0;
  PyObject *n_idx_capi = Py_None;
  int *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int m_y = 0;
  PyObject *m_y_capi = Py_None;
  int l = 0;
  PyObject *l_capi = Py_None;
  double *x_oh_pinv1 = NULL;
  npy_intp x_oh_pinv1_Dims[2] = {-1, -1};
  const int x_oh_pinv1_Rank = 2;
  PyArrayObject *capi_x_oh_pinv1_tmp = NULL;
  int capi_x_oh_pinv1_intent = 0;
  PyObject *x_oh_pinv1_capi = Py_None;
  double *x_oh_pinv2 = NULL;
  npy_intp x_oh_pinv2_Dims[1] = {-1};
  const int x_oh_pinv2_Rank = 1;
  PyArrayObject *capi_x_oh_pinv2_tmp = NULL;
  int capi_x_oh_pinv2_intent = 0;
  PyObject *x_oh_pinv2_capi = Py_None;
  double *x_oh_pinv3 = NULL;
  npy_intp x_oh_pinv3_Dims[2] = {-1, -1};
  const int x_oh_pinv3_Rank = 2;
  PyArrayObject *capi_x_oh_pinv3_tmp = NULL;
  int capi_x_oh_pinv3_intent = 0;
  PyObject *x_oh_pinv3_capi = Py_None;
  int x_oh_rank = 0;
  PyObject *x_oh_rank_capi = Py_None;
  int n_s = 0;
  PyObject *n_s_capi = Py_None;
  int iters = 0;
  PyObject *iters_capi = Py_None;
  int overfit = 0;
  PyObject *overfit_capi = Py_None;
  int impute = 0;
  PyObject *impute_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[2] = {-1, -1};
  const int w_Rank = 2;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  double *disc = NULL;
  npy_intp disc_Dims[1] = {-1};
  const int disc_Rank = 1;
  PyArrayObject *capi_disc_tmp = NULL;
  int capi_disc_intent = 0;
  int iter = 0;
  static char *capi_kwlist[] = {"i1","i2","s","y","m_y","x_oh_pinv1","x_oh_pinv2","x_oh_pinv3","iters","overfit","impute","n_idx","l","x_oh_rank","n_s",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|OOOO:fortran_module.fortran_module.discrete_fit_i",\
    capi_kwlist,&i1_capi,&i2_capi,&s_capi,&y_capi,&m_y_capi,&x_oh_pinv1_capi,&x_oh_pinv2_capi,&x_oh_pinv3_capi,&iters_capi,&overfit_capi,&impute_capi,&n_idx_capi,&l_capi,&x_oh_rank_capi,&n_s_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable i1 */
    f2py_success = int_from_pyobj(&i1,i1_capi,"fortran_module.fortran_module.discrete_fit_i() 1st argument (i1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable i2 */
    f2py_success = int_from_pyobj(&i2,i2_capi,"fortran_module.fortran_module.discrete_fit_i() 2nd argument (i2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable overfit */
    overfit = (int)PyObject_IsTrue(overfit_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable s */
  ;
  capi_s_intent |= F2PY_INTENT_IN;
  capi_s_tmp = array_from_pyobj(NPY_INT,s_Dims,s_Rank,capi_s_intent,s_capi);
  if (capi_s_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 3rd argument `s' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    s = (int *)(PyArray_DATA(capi_s_tmp));

  /* Processing variable iter */
  /* Processing variable iters */
    f2py_success = int_from_pyobj(&iters,iters_capi,"fortran_module.fortran_module.discrete_fit_i() 9th argument (iters) can't be converted to int");
  if (f2py_success) {
  /* Processing variable m_y */
    f2py_success = int_from_pyobj(&m_y,m_y_capi,"fortran_module.fortran_module.discrete_fit_i() 5th argument (m_y) can't be converted to int");
  if (f2py_success) {
  /* Processing variable impute */
    impute = (int)PyObject_IsTrue(impute_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable n_idx */
  if (n_idx_capi == Py_None) n_idx = shape(s,0); else
    f2py_success = int_from_pyobj(&n_idx,n_idx_capi,"fortran_module.fortran_module.discrete_fit_i() 1st keyword (n_idx) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(s,0)==n_idx,"shape(s,0)==n_idx","1st keyword n_idx","discrete_fit_i:n_idx=%d",n_idx) {
  /* Processing variable disc */
  disc_Dims[0]=iters;
  capi_disc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_disc_tmp = array_from_pyobj(NPY_DOUBLE,disc_Dims,disc_Rank,capi_disc_intent,Py_None);
  if (capi_disc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `disc' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    disc = (double *)(PyArray_DATA(capi_disc_tmp));

  /* Processing variable l */
  if (l_capi == Py_None) l = shape(s,1); else
    f2py_success = int_from_pyobj(&l,l_capi,"fortran_module.fortran_module.discrete_fit_i() 2nd keyword (l) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(s,1)==l,"shape(s,1)==l","2nd keyword l","discrete_fit_i:l=%d",l) {
  /* Processing variable x_oh_pinv1 */
  x_oh_pinv1_Dims[0]=l;
  capi_x_oh_pinv1_intent |= F2PY_INTENT_IN;
  capi_x_oh_pinv1_tmp = array_from_pyobj(NPY_DOUBLE,x_oh_pinv1_Dims,x_oh_pinv1_Rank,capi_x_oh_pinv1_intent,x_oh_pinv1_capi);
  if (capi_x_oh_pinv1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 6th argument `x_oh_pinv1' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    x_oh_pinv1 = (double *)(PyArray_DATA(capi_x_oh_pinv1_tmp));

  /* Processing variable y */
  y_Dims[0]=l;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_INT,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 4th argument `y' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    y = (int *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable x_oh_rank */
  if (x_oh_rank_capi == Py_None) x_oh_rank = shape(x_oh_pinv1,1); else
    f2py_success = int_from_pyobj(&x_oh_rank,x_oh_rank_capi,"fortran_module.fortran_module.discrete_fit_i() 3rd keyword (x_oh_rank) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(x_oh_pinv1,1)==x_oh_rank,"shape(x_oh_pinv1,1)==x_oh_rank","3rd keyword x_oh_rank","discrete_fit_i:x_oh_rank=%d",x_oh_rank) {
  /* Processing variable x_oh_pinv2 */
  x_oh_pinv2_Dims[0]=x_oh_rank;
  capi_x_oh_pinv2_intent |= F2PY_INTENT_IN;
  capi_x_oh_pinv2_tmp = array_from_pyobj(NPY_DOUBLE,x_oh_pinv2_Dims,x_oh_pinv2_Rank,capi_x_oh_pinv2_intent,x_oh_pinv2_capi);
  if (capi_x_oh_pinv2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 7th argument `x_oh_pinv2' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    x_oh_pinv2 = (double *)(PyArray_DATA(capi_x_oh_pinv2_tmp));

  /* Processing variable x_oh_pinv3 */
  x_oh_pinv3_Dims[0]=x_oh_rank;
  capi_x_oh_pinv3_intent |= F2PY_INTENT_IN;
  capi_x_oh_pinv3_tmp = array_from_pyobj(NPY_DOUBLE,x_oh_pinv3_Dims,x_oh_pinv3_Rank,capi_x_oh_pinv3_intent,x_oh_pinv3_capi);
  if (capi_x_oh_pinv3_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 8th argument `x_oh_pinv3' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    x_oh_pinv3 = (double *)(PyArray_DATA(capi_x_oh_pinv3_tmp));

  /* Processing variable n_s */
  if (n_s_capi == Py_None) n_s = shape(x_oh_pinv3,1); else
    f2py_success = int_from_pyobj(&n_s,n_s_capi,"fortran_module.fortran_module.discrete_fit_i() 4th keyword (n_s) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(x_oh_pinv3,1)==n_s,"shape(x_oh_pinv3,1)==n_s","4th keyword n_s","discrete_fit_i:n_s=%d",n_s) {
  /* Processing variable w */
  w_Dims[0]=m_y,w_Dims[1]=n_s;
  capi_w_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `w' of fortran_module.fortran_module.discrete_fit_i to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&i1,&i2,s,&n_idx,y,&m_y,&l,x_oh_pinv1,x_oh_pinv2,x_oh_pinv3,&x_oh_rank,&n_s,&iters,&overfit,&impute,w,disc,&iter);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNi",capi_w_tmp,capi_disc_tmp,iter);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  } /*CHECKSCALAR(shape(x_oh_pinv3,1)==n_s)*/
  } /*if (f2py_success) of n_s*/
  /* End of cleaning variable n_s */
  if((PyObject *)capi_x_oh_pinv3_tmp!=x_oh_pinv3_capi) {
    Py_XDECREF(capi_x_oh_pinv3_tmp); }
  }  /*if (capi_x_oh_pinv3_tmp == NULL) ... else of x_oh_pinv3*/
  /* End of cleaning variable x_oh_pinv3 */
  if((PyObject *)capi_x_oh_pinv2_tmp!=x_oh_pinv2_capi) {
    Py_XDECREF(capi_x_oh_pinv2_tmp); }
  }  /*if (capi_x_oh_pinv2_tmp == NULL) ... else of x_oh_pinv2*/
  /* End of cleaning variable x_oh_pinv2 */
  } /*CHECKSCALAR(shape(x_oh_pinv1,1)==x_oh_rank)*/
  } /*if (f2py_success) of x_oh_rank*/
  /* End of cleaning variable x_oh_rank */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_x_oh_pinv1_tmp!=x_oh_pinv1_capi) {
    Py_XDECREF(capi_x_oh_pinv1_tmp); }
  }  /*if (capi_x_oh_pinv1_tmp == NULL) ... else of x_oh_pinv1*/
  /* End of cleaning variable x_oh_pinv1 */
  } /*CHECKSCALAR(shape(s,1)==l)*/
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
  }  /*if (capi_disc_tmp == NULL) ... else of disc*/
  /* End of cleaning variable disc */
  } /*CHECKSCALAR(shape(s,0)==n_idx)*/
  } /*if (f2py_success) of n_idx*/
  /* End of cleaning variable n_idx */
  } /*if (f2py_success) of impute*/
  /* End of cleaning variable impute */
  } /*if (f2py_success) of m_y*/
  /* End of cleaning variable m_y */
  } /*if (f2py_success) of iters*/
  /* End of cleaning variable iters */
  /* End of cleaning variable iter */
  if((PyObject *)capi_s_tmp!=s_capi) {
    Py_XDECREF(capi_s_tmp); }
  }  /*if (capi_s_tmp == NULL) ... else of s*/
  /* End of cleaning variable s */
  } /*if (f2py_success) of overfit*/
  /* End of cleaning variable overfit */
  } /*if (f2py_success) of i2*/
  /* End of cleaning variable i2 */
  } /*if (f2py_success) of i1*/
  /* End of cleaning variable i1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of discrete_fit_i ***************************/

/******************************* continuous_fit *******************************/
static char doc_f2py_rout_fortran_module_fortran_module_continuous_fit[] = "\
w,disc,iter = continuous_fit(x,y,iters,atol,rtol,impute,[l])\n\nWrapper for ``continuous_fit``.\
\n\nParameters\n----------\n"
"x : input rank-2 array('d') with bounds (n,l)\n"
"y : input rank-2 array('d') with bounds (n,l)\n"
"iters : input int\n"
"atol : input float\n"
"rtol : input float\n"
"impute : input int\n"
"\nOther Parameters\n----------------\n"
"l : input int, optional\n    Default: shape(x,1)\n"
"\nReturns\n-------\n"
"w : rank-2 array('d') with bounds (n,n)\n"
"disc : rank-2 array('d') with bounds (n,iters)\n"
"iter : rank-1 array('i') with bounds (n)";
/*  */
static PyObject *f2py_rout_fortran_module_fortran_module_continuous_fit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*,double*,double*,int*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[2] = {-1, -1};
  const int x_Rank = 2;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *y = NULL;
  npy_intp y_Dims[2] = {-1, -1};
  const int y_Rank = 2;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int n = 0;
  int l = 0;
  PyObject *l_capi = Py_None;
  int iters = 0;
  PyObject *iters_capi = Py_None;
  double atol = 0;
  PyObject *atol_capi = Py_None;
  double rtol = 0;
  PyObject *rtol_capi = Py_None;
  int impute = 0;
  PyObject *impute_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[2] = {-1, -1};
  const int w_Rank = 2;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  double *disc = NULL;
  npy_intp disc_Dims[2] = {-1, -1};
  const int disc_Rank = 2;
  PyArrayObject *capi_disc_tmp = NULL;
  int capi_disc_intent = 0;
  int *iter = NULL;
  npy_intp iter_Dims[1] = {-1};
  const int iter_Rank = 1;
  PyArrayObject *capi_iter_tmp = NULL;
  int capi_iter_intent = 0;
  static char *capi_kwlist[] = {"x","y","iters","atol","rtol","impute","l",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:fortran_module.fortran_module.continuous_fit",\
    capi_kwlist,&x_capi,&y_capi,&iters_capi,&atol_capi,&rtol_capi,&impute_capi,&l_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rtol */
    f2py_success = double_from_pyobj(&rtol,rtol_capi,"fortran_module.fortran_module.continuous_fit() 5th argument (rtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable atol */
    f2py_success = double_from_pyobj(&atol,atol_capi,"fortran_module.fortran_module.continuous_fit() 4th argument (atol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable iters */
    f2py_success = int_from_pyobj(&iters,iters_capi,"fortran_module.fortran_module.continuous_fit() 3rd argument (iters) can't be converted to int");
  if (f2py_success) {
  /* Processing variable impute */
    impute = (int)PyObject_IsTrue(impute_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 1st argument `x' of fortran_module.fortran_module.continuous_fit to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable l */
  if (l_capi == Py_None) l = shape(x,1); else
    f2py_success = int_from_pyobj(&l,l_capi,"fortran_module.fortran_module.continuous_fit() 1st keyword (l) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(x,1)==l,"shape(x,1)==l","1st keyword l","continuous_fit:l=%d",l) {
  /* Processing variable n */
  n = shape(x,0);
  /* Processing variable disc */
  disc_Dims[0]=n,disc_Dims[1]=iters;
  capi_disc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_disc_tmp = array_from_pyobj(NPY_DOUBLE,disc_Dims,disc_Rank,capi_disc_intent,Py_None);
  if (capi_disc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `disc' of fortran_module.fortran_module.continuous_fit to C/Fortran array" );
  } else {
    disc = (double *)(PyArray_DATA(capi_disc_tmp));

  /* Processing variable w */
  w_Dims[0]=n,w_Dims[1]=n;
  capi_w_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `w' of fortran_module.fortran_module.continuous_fit to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

  /* Processing variable y */
  y_Dims[0]=n,y_Dims[1]=l;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 2nd argument `y' of fortran_module.fortran_module.continuous_fit to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable iter */
  iter_Dims[0]=n;
  capi_iter_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_iter_tmp = array_from_pyobj(NPY_INT,iter_Dims,iter_Rank,capi_iter_intent,Py_None);
  if (capi_iter_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `iter' of fortran_module.fortran_module.continuous_fit to C/Fortran array" );
  } else {
    iter = (int *)(PyArray_DATA(capi_iter_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,y,&n,&l,&iters,&atol,&rtol,&impute,w,disc,iter);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNN",capi_w_tmp,capi_disc_tmp,capi_iter_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_iter_tmp == NULL) ... else of iter*/
  /* End of cleaning variable iter */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  }  /*if (capi_disc_tmp == NULL) ... else of disc*/
  /* End of cleaning variable disc */
  /* End of cleaning variable n */
  } /*CHECKSCALAR(shape(x,1)==l)*/
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of impute*/
  /* End of cleaning variable impute */
  } /*if (f2py_success) of iters*/
  /* End of cleaning variable iters */
  } /*if (f2py_success) of atol*/
  /* End of cleaning variable atol */
  } /*if (f2py_success) of rtol*/
  /* End of cleaning variable rtol */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of continuous_fit ***************************/

/****************************** continuous_fit_i ******************************/
static char doc_f2py_rout_fortran_module_fortran_module_continuous_fit_i[] = "\
w,disc,iter = continuous_fit_i(i,x,x_mean0,symx,cov_x,ipiv,iters,atol,rtol,impute,[n,l])\n\nWrapper for ``continuous_fit_i``.\
\n\nParameters\n----------\n"
"i : input int\n"
"x : input rank-2 array('d') with bounds (n,l)\n"
"x_mean0 : input rank-2 array('d') with bounds (n,l)\n"
"symx : input rank-1 array('d') with bounds (l)\n"
"cov_x : input rank-2 array('d') with bounds (n,n)\n"
"ipiv : input rank-1 array('i') with bounds (n)\n"
"iters : input int\n"
"atol : input float\n"
"rtol : input float\n"
"impute : input int\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(x,0)\n"
"l : input int, optional\n    Default: shape(x,1)\n"
"\nReturns\n-------\n"
"w : rank-1 array('d') with bounds (n)\n"
"disc : rank-1 array('d') with bounds (iters)\n"
"iter : int";
/*  */
static PyObject *f2py_rout_fortran_module_fortran_module_continuous_fit_i(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,double*,double*,int*,int*,double*,double*,int*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int i = 0;
  PyObject *i_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[2] = {-1, -1};
  const int x_Rank = 2;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int l = 0;
  PyObject *l_capi = Py_None;
  double *x_mean0 = NULL;
  npy_intp x_mean0_Dims[2] = {-1, -1};
  const int x_mean0_Rank = 2;
  PyArrayObject *capi_x_mean0_tmp = NULL;
  int capi_x_mean0_intent = 0;
  PyObject *x_mean0_capi = Py_None;
  double *symx = NULL;
  npy_intp symx_Dims[1] = {-1};
  const int symx_Rank = 1;
  PyArrayObject *capi_symx_tmp = NULL;
  int capi_symx_intent = 0;
  PyObject *symx_capi = Py_None;
  double *cov_x = NULL;
  npy_intp cov_x_Dims[2] = {-1, -1};
  const int cov_x_Rank = 2;
  PyArrayObject *capi_cov_x_tmp = NULL;
  int capi_cov_x_intent = 0;
  PyObject *cov_x_capi = Py_None;
  int *ipiv = NULL;
  npy_intp ipiv_Dims[1] = {-1};
  const int ipiv_Rank = 1;
  PyArrayObject *capi_ipiv_tmp = NULL;
  int capi_ipiv_intent = 0;
  PyObject *ipiv_capi = Py_None;
  int iters = 0;
  PyObject *iters_capi = Py_None;
  double atol = 0;
  PyObject *atol_capi = Py_None;
  double rtol = 0;
  PyObject *rtol_capi = Py_None;
  int impute = 0;
  PyObject *impute_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  double *disc = NULL;
  npy_intp disc_Dims[1] = {-1};
  const int disc_Rank = 1;
  PyArrayObject *capi_disc_tmp = NULL;
  int capi_disc_intent = 0;
  int iter = 0;
  static char *capi_kwlist[] = {"i","x","x_mean0","symx","cov_x","ipiv","iters","atol","rtol","impute","n","l",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|OO:fortran_module.fortran_module.continuous_fit_i",\
    capi_kwlist,&i_capi,&x_capi,&x_mean0_capi,&symx_capi,&cov_x_capi,&ipiv_capi,&iters_capi,&atol_capi,&rtol_capi,&impute_capi,&n_capi,&l_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable rtol */
    f2py_success = double_from_pyobj(&rtol,rtol_capi,"fortran_module.fortran_module.continuous_fit_i() 9th argument (rtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable atol */
    f2py_success = double_from_pyobj(&atol,atol_capi,"fortran_module.fortran_module.continuous_fit_i() 8th argument (atol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable i */
    f2py_success = int_from_pyobj(&i,i_capi,"fortran_module.fortran_module.continuous_fit_i() 1st argument (i) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iter */
  /* Processing variable iters */
    f2py_success = int_from_pyobj(&iters,iters_capi,"fortran_module.fortran_module.continuous_fit_i() 7th argument (iters) can't be converted to int");
  if (f2py_success) {
  /* Processing variable impute */
    impute = (int)PyObject_IsTrue(impute_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 2nd argument `x' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable l */
  if (l_capi == Py_None) l = shape(x,1); else
    f2py_success = int_from_pyobj(&l,l_capi,"fortran_module.fortran_module.continuous_fit_i() 2nd keyword (l) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(x,1)==l,"shape(x,1)==l","2nd keyword l","continuous_fit_i:l=%d",l) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(x,0); else
    f2py_success = int_from_pyobj(&n,n_capi,"fortran_module.fortran_module.continuous_fit_i() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(x,0)==n,"shape(x,0)==n","1st keyword n","continuous_fit_i:n=%d",n) {
  /* Processing variable disc */
  disc_Dims[0]=iters;
  capi_disc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_disc_tmp = array_from_pyobj(NPY_DOUBLE,disc_Dims,disc_Rank,capi_disc_intent,Py_None);
  if (capi_disc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `disc' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    disc = (double *)(PyArray_DATA(capi_disc_tmp));

  /* Processing variable w */
  w_Dims[0]=n;
  capi_w_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting hidden `w' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

  /* Processing variable symx */
  symx_Dims[0]=l;
  capi_symx_intent |= F2PY_INTENT_IN;
  capi_symx_tmp = array_from_pyobj(NPY_DOUBLE,symx_Dims,symx_Rank,capi_symx_intent,symx_capi);
  if (capi_symx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 4th argument `symx' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    symx = (double *)(PyArray_DATA(capi_symx_tmp));

  /* Processing variable cov_x */
  cov_x_Dims[0]=n,cov_x_Dims[1]=n;
  capi_cov_x_intent |= F2PY_INTENT_IN;
  capi_cov_x_tmp = array_from_pyobj(NPY_DOUBLE,cov_x_Dims,cov_x_Rank,capi_cov_x_intent,cov_x_capi);
  if (capi_cov_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 5th argument `cov_x' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    cov_x = (double *)(PyArray_DATA(capi_cov_x_tmp));

  /* Processing variable ipiv */
  ipiv_Dims[0]=n;
  capi_ipiv_intent |= F2PY_INTENT_IN;
  capi_ipiv_tmp = array_from_pyobj(NPY_INT,ipiv_Dims,ipiv_Rank,capi_ipiv_intent,ipiv_capi);
  if (capi_ipiv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 6th argument `ipiv' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    ipiv = (int *)(PyArray_DATA(capi_ipiv_tmp));

  /* Processing variable x_mean0 */
  x_mean0_Dims[0]=n,x_mean0_Dims[1]=l;
  capi_x_mean0_intent |= F2PY_INTENT_IN;
  capi_x_mean0_tmp = array_from_pyobj(NPY_DOUBLE,x_mean0_Dims,x_mean0_Rank,capi_x_mean0_intent,x_mean0_capi);
  if (capi_x_mean0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_module_error,"failed in converting 3rd argument `x_mean0' of fortran_module.fortran_module.continuous_fit_i to C/Fortran array" );
  } else {
    x_mean0 = (double *)(PyArray_DATA(capi_x_mean0_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&i,x,&n,&l,x_mean0,symx,cov_x,ipiv,&iters,&atol,&rtol,&impute,w,disc,&iter);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNi",capi_w_tmp,capi_disc_tmp,iter);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_x_mean0_tmp!=x_mean0_capi) {
    Py_XDECREF(capi_x_mean0_tmp); }
  }  /*if (capi_x_mean0_tmp == NULL) ... else of x_mean0*/
  /* End of cleaning variable x_mean0 */
  if((PyObject *)capi_ipiv_tmp!=ipiv_capi) {
    Py_XDECREF(capi_ipiv_tmp); }
  }  /*if (capi_ipiv_tmp == NULL) ... else of ipiv*/
  /* End of cleaning variable ipiv */
  if((PyObject *)capi_cov_x_tmp!=cov_x_capi) {
    Py_XDECREF(capi_cov_x_tmp); }
  }  /*if (capi_cov_x_tmp == NULL) ... else of cov_x*/
  /* End of cleaning variable cov_x */
  if((PyObject *)capi_symx_tmp!=symx_capi) {
    Py_XDECREF(capi_symx_tmp); }
  }  /*if (capi_symx_tmp == NULL) ... else of symx*/
  /* End of cleaning variable symx */
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  }  /*if (capi_disc_tmp == NULL) ... else of disc*/
  /* End of cleaning variable disc */
  } /*CHECKSCALAR(shape(x,0)==n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(shape(x,1)==l)*/
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of impute*/
  /* End of cleaning variable impute */
  } /*if (f2py_success) of iters*/
  /* End of cleaning variable iters */
  /* End of cleaning variable iter */
  } /*if (f2py_success) of i*/
  /* End of cleaning variable i */
  } /*if (f2py_success) of atol*/
  /* End of cleaning variable atol */
  } /*if (f2py_success) of rtol*/
  /* End of cleaning variable rtol */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of continuous_fit_i **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_fortran_module_def[] = {
  {"num_threads",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_num_threads,doc_f2py_rout_fortran_module_fortran_module_num_threads},
  {"multiindices",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_multiindices,doc_f2py_rout_fortran_module_fortran_module_multiindices},
  {"simulate_time_series",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_simulate_time_series,doc_f2py_rout_fortran_module_fortran_module_simulate_time_series},
  {"simulate_mutations",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_simulate_mutations,doc_f2py_rout_fortran_module_fortran_module_simulate_mutations},
  {"discrete_fit",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_discrete_fit,doc_f2py_rout_fortran_module_fortran_module_discrete_fit},
  {"discrete_fit_i",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_discrete_fit_i,doc_f2py_rout_fortran_module_fortran_module_discrete_fit_i},
  {"continuous_fit",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_continuous_fit,doc_f2py_rout_fortran_module_fortran_module_continuous_fit},
  {"continuous_fit_i",-1,{{-1}},0,NULL,(void *)f2py_rout_fortran_module_fortran_module_continuous_fit_i,doc_f2py_rout_fortran_module_fortran_module_continuous_fit_i},
  {NULL}
};

static void f2py_setup_fortran_module(char *num_threads,char *multiindices,char *simulate_time_series,char *simulate_mutations,char *discrete_fit,char *discrete_fit_i,char *continuous_fit,char *continuous_fit_i) {
  int i_f2py=0;
  f2py_fortran_module_def[i_f2py++].data = num_threads;
  f2py_fortran_module_def[i_f2py++].data = multiindices;
  f2py_fortran_module_def[i_f2py++].data = simulate_time_series;
  f2py_fortran_module_def[i_f2py++].data = simulate_mutations;
  f2py_fortran_module_def[i_f2py++].data = discrete_fit;
  f2py_fortran_module_def[i_f2py++].data = discrete_fit_i;
  f2py_fortran_module_def[i_f2py++].data = continuous_fit;
  f2py_fortran_module_def[i_f2py++].data = continuous_fit_i;
}
extern void F_FUNC_US(f2pyinitfortran_module,F2PYINITFORTRAN_MODULE)(void (*)(char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_fortran_module(void) {
  F_FUNC_US(f2pyinitfortran_module,F2PYINITFORTRAN_MODULE)(f2py_setup_fortran_module);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "fortran_module",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_fortran_module(void) {
#else
#define RETVAL
PyMODINIT_FUNC initfortran_module(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = fortran_module_module = PyModule_Create(&moduledef);
#else
  m = fortran_module_module = Py_InitModule("fortran_module", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module fortran_module (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'fortran_module' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  fortran_module --- num_threads(),multiindices(),simulate_time_series(),simulate_mutations(),discrete_fit(),discrete_fit_i(),continuous_fit(),continuous_fit_i()"".");
  PyDict_SetItemString(d, "__doc__", s);
  fortran_module_error = PyErr_NewException ("fortran_module.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "fortran_module", PyFortranObject_New(f2py_fortran_module_def,f2py_init_fortran_module));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"fortran_module");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
